import sys
from PyQt4.QtGui import*
uyg=QApplication(sys.argv)
pencere=QWidget()
pencere.setWindowTitle('Akaryakıt Hesaplama')
yol=QLabel('<font color="blue" size="5">Gideceğiniz Yol:</font>')
fiyat=QLabel('<font color="blue" size="5">Yakıt Fiyatı:</font>')
km=QLabel('<font color="blue" size="5">100 km de Tüketilen Yakıt:</font>')
yoL=QLineEdit()
fiyaT=QLineEdit()
kM=QLineEdit()
sonuc=QLabel('<font color="blue" size="5">Toplam Tutar</font>')
buton=QPushButton("HESAPLA")
button=QPushButton("TEMİZLE")
sonuC=QLabel('<b>0.00</b>')
solKutu=QVBoxLayout()
sagKutu=QVBoxLayout()
ortalama=QHBoxLayout()
solKutu.addWidget(yol)
solKutu.addWidget(fiyat)
solKutu.addWidget(km)
solKutu.addWidget(sonuc)
sagKutu.addWidget(yoL)
sagKutu.addWidget(fiyaT)
sagKutu.addWidget(kM)
sagKutu.addWidget(sonuC)
solKutu.addWidget(buton)
sagKutu.addWidget(button)
ortalama.addLayout(solKutu)
ortalama.addLayout(sagKutu)
pencere.setLayout(ortalama)
pencere.show()
uyg.exec_
